# Generated by Django 4.2.10 on 2025-05-05 21:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import study_materials.models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("courses", "0001_initial"),
        ("university_structure", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ElectronicLibrarySystem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Название")),
                ("url", models.URLField(verbose_name="URL системы")),
                ("description", models.TextField(blank=True, verbose_name="Описание")),
                (
                    "logo",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="elib_logos/",
                        verbose_name="Логотип",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Активна"),
                ),
                (
                    "subscription_start",
                    models.DateField(
                        blank=True, null=True, verbose_name="Начало подписки"
                    ),
                ),
                (
                    "subscription_end",
                    models.DateField(
                        blank=True, null=True, verbose_name="Окончание подписки"
                    ),
                ),
                (
                    "access_instructions",
                    models.TextField(blank=True, verbose_name="Инструкции по доступу"),
                ),
            ],
            options={
                "verbose_name": "электронная библиотечная система",
                "verbose_name_plural": "электронные библиотечные системы",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Material",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="Заголовок")),
                (
                    "slug",
                    models.SlugField(
                        blank=True, max_length=255, verbose_name="URL-идентификатор"
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="Описание")),
                (
                    "material_type",
                    models.CharField(
                        choices=[
                            ("lecture", "Лекция"),
                            ("practice", "Практическое занятие"),
                            ("lab", "Лабораторная работа"),
                            ("seminar", "Семинар"),
                            ("textbook", "Учебник"),
                            ("manual", "Методическое пособие"),
                            ("article", "Статья"),
                            ("video", "Видео"),
                            ("presentation", "Презентация"),
                            ("test", "Тест/Контрольная работа"),
                            ("exam", "Экзаменационные материалы"),
                            ("literature", "Литература"),
                            ("other", "Другое"),
                        ],
                        max_length=20,
                        verbose_name="Тип материала",
                    ),
                ),
                (
                    "content",
                    models.TextField(blank=True, verbose_name="Текстовое содержимое"),
                ),
                (
                    "file",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to=study_materials.models.get_material_file_path,
                        verbose_name="Файл",
                    ),
                ),
                (
                    "file_size",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Размер файла (байт)"
                    ),
                ),
                (
                    "file_type",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Тип файла"
                    ),
                ),
                (
                    "external_url",
                    models.URLField(blank=True, verbose_name="Внешняя ссылка"),
                ),
                (
                    "access_level",
                    models.CharField(
                        choices=[
                            ("public", "Публичный"),
                            ("university", "Для всего университета"),
                            ("faculty", "Для факультета"),
                            ("department", "Для кафедры"),
                            ("group", "Для групп"),
                            ("course", "Для курса"),
                            ("private", "Приватный"),
                        ],
                        default="group",
                        max_length=20,
                        verbose_name="Уровень доступа",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
                ),
                (
                    "is_published",
                    models.BooleanField(default=True, verbose_name="Опубликован"),
                ),
                (
                    "is_featured",
                    models.BooleanField(default=False, verbose_name="Рекомендуемый"),
                ),
                (
                    "academic_plan_subject",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="materials",
                        to="university_structure.academicplansubject",
                        verbose_name="Предмет учебного плана",
                    ),
                ),
                (
                    "author",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_materials",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Автор",
                    ),
                ),
            ],
            options={
                "verbose_name": "учебный материал",
                "verbose_name_plural": "учебные материалы",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="MaterialTag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="Название"
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        blank=True, unique=True, verbose_name="URL-идентификатор"
                    ),
                ),
            ],
            options={
                "verbose_name": "тег материала",
                "verbose_name_plural": "теги материалов",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="MaterialView",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "viewed_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата просмотра"
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="IP-адрес"
                    ),
                ),
                (
                    "material",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="views",
                        to="study_materials.material",
                        verbose_name="Материал",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="material_views",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь",
                    ),
                ),
            ],
            options={
                "verbose_name": "просмотр материала",
                "verbose_name_plural": "просмотры материалов",
                "ordering": ["-viewed_at"],
            },
        ),
        migrations.CreateModel(
            name="MaterialDownload",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "downloaded_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата скачивания"
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="IP-адрес"
                    ),
                ),
                ("user_agent", models.TextField(blank=True, verbose_name="User-Agent")),
                (
                    "material",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="downloads",
                        to="study_materials.material",
                        verbose_name="Материал",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="material_downloads",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь",
                    ),
                ),
            ],
            options={
                "verbose_name": "скачивание материала",
                "verbose_name_plural": "скачивания материалов",
                "ordering": ["-downloaded_at"],
            },
        ),
        migrations.CreateModel(
            name="MaterialComment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.TextField(verbose_name="Текст комментария")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
                ),
                (
                    "is_approved",
                    models.BooleanField(default=True, verbose_name="Одобрен"),
                ),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="material_comments",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Автор",
                    ),
                ),
                (
                    "material",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to="study_materials.material",
                        verbose_name="Материал",
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="replies",
                        to="study_materials.materialcomment",
                        verbose_name="Родительский комментарий",
                    ),
                ),
            ],
            options={
                "verbose_name": "комментарий к материалу",
                "verbose_name_plural": "комментарии к материалам",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="MaterialCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Название")),
                ("description", models.TextField(blank=True, verbose_name="Описание")),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subcategories",
                        to="study_materials.materialcategory",
                        verbose_name="Родительская категория",
                    ),
                ),
            ],
            options={
                "verbose_name": "категория материалов",
                "verbose_name_plural": "категории материалов",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="MaterialAttachment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="Заголовок")),
                ("description", models.TextField(blank=True, verbose_name="Описание")),
                (
                    "file",
                    models.FileField(
                        upload_to="material_attachments/", verbose_name="Файл"
                    ),
                ),
                (
                    "file_size",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Размер файла (байт)"
                    ),
                ),
                (
                    "file_type",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Тип файла"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "material",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attachments",
                        to="study_materials.material",
                        verbose_name="Материал",
                    ),
                ),
            ],
            options={
                "verbose_name": "вложение к материалу",
                "verbose_name_plural": "вложения к материалам",
            },
        ),
        migrations.AddField(
            model_name="material",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="materials",
                to="study_materials.materialcategory",
                verbose_name="Категория",
            ),
        ),
        migrations.AddField(
            model_name="material",
            name="courses",
            field=models.ManyToManyField(
                blank=True,
                related_name="materials",
                to="courses.course",
                verbose_name="Курсы",
            ),
        ),
        migrations.AddField(
            model_name="material",
            name="groups",
            field=models.ManyToManyField(
                blank=True,
                related_name="available_materials",
                to="university_structure.group",
                verbose_name="Группы",
            ),
        ),
        migrations.AddField(
            model_name="material",
            name="subject",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="materials",
                to="university_structure.subject",
                verbose_name="Предмет",
            ),
        ),
        migrations.AddField(
            model_name="material",
            name="tags",
            field=models.ManyToManyField(
                blank=True,
                related_name="materials",
                to="study_materials.materialtag",
                verbose_name="Теги",
            ),
        ),
        migrations.CreateModel(
            name="Literature",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="Название")),
                ("authors", models.CharField(max_length=255, verbose_name="Авторы")),
                (
                    "publication_year",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="Год публикации"
                    ),
                ),
                (
                    "publisher",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Издательство"
                    ),
                ),
                (
                    "isbn",
                    models.CharField(blank=True, max_length=20, verbose_name="ISBN"),
                ),
                ("description", models.TextField(blank=True, verbose_name="Описание")),
                (
                    "literature_type",
                    models.CharField(
                        choices=[
                            ("textbook", "Учебник"),
                            ("manual", "Учебное пособие"),
                            ("monograph", "Монография"),
                            ("article", "Статья"),
                            ("reference", "Справочник"),
                            ("periodical", "Периодическое издание"),
                            ("other", "Другое"),
                        ],
                        max_length=20,
                        verbose_name="Тип литературы",
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="literature/",
                        verbose_name="Файл",
                    ),
                ),
                (
                    "file_size",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Размер файла (байт)"
                    ),
                ),
                (
                    "external_url",
                    models.URLField(blank=True, verbose_name="Внешняя ссылка"),
                ),
                (
                    "availability",
                    models.CharField(
                        choices=[
                            ("available", "В наличии"),
                            ("limited", "Ограниченное количество"),
                            ("unavailable", "Отсутствует"),
                            ("electronic", "Только электронная версия"),
                        ],
                        default="available",
                        max_length=20,
                        verbose_name="Доступность",
                    ),
                ),
                (
                    "copies_available",
                    models.PositiveSmallIntegerField(
                        default=0, verbose_name="Доступных экземпляров"
                    ),
                ),
                (
                    "location",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Местонахождение"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
                ),
                (
                    "added_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="added_literature",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Добавил",
                    ),
                ),
                (
                    "subjects",
                    models.ManyToManyField(
                        blank=True,
                        related_name="literature",
                        to="university_structure.subject",
                        verbose_name="Дисциплины",
                    ),
                ),
            ],
            options={
                "verbose_name": "литература",
                "verbose_name_plural": "литература",
                "ordering": ["title"],
            },
        ),
        migrations.CreateModel(
            name="MaterialRating",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "rating",
                    models.PositiveSmallIntegerField(
                        choices=[(1, "1"), (2, "2"), (3, "3"), (4, "4"), (5, "5")],
                        verbose_name="Оценка",
                    ),
                ),
                ("comment", models.TextField(blank=True, verbose_name="Комментарий")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
                ),
                (
                    "material",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ratings",
                        to="study_materials.material",
                        verbose_name="Материал",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="material_ratings",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь",
                    ),
                ),
            ],
            options={
                "verbose_name": "оценка материала",
                "verbose_name_plural": "оценки материалов",
                "unique_together": {("material", "user")},
            },
        ),
        migrations.CreateModel(
            name="MaterialFavorite",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "added_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата добавления"
                    ),
                ),
                (
                    "material",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="favorites",
                        to="study_materials.material",
                        verbose_name="Материал",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="favorite_materials",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь",
                    ),
                ),
            ],
            options={
                "verbose_name": "избранный материал",
                "verbose_name_plural": "избранные материалы",
                "ordering": ["-added_at"],
                "unique_together": {("material", "user")},
            },
        ),
    ]
