# Generated by Django 4.2.10 on 2025-05-05 21:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AdminProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "position",
                    models.CharField(max_length=100, verbose_name="Должность"),
                ),
                (
                    "access_level",
                    models.IntegerField(
                        choices=[
                            (1, "Базовый"),
                            (2, "Расширенный"),
                            (3, "Продвинутый"),
                            (4, "Экспертный"),
                            (5, "Полный"),
                        ],
                        default=1,
                        verbose_name="Уровень доступа",
                    ),
                ),
                (
                    "responsibility_area",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        verbose_name="Область ответственности",
                    ),
                ),
            ],
            options={
                "verbose_name": "профиль администратора",
                "verbose_name_plural": "профили администраторов",
            },
        ),
        migrations.CreateModel(
            name="DeanProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "employee_id",
                    models.CharField(
                        max_length=20, unique=True, verbose_name="Табельный номер"
                    ),
                ),
                (
                    "position",
                    models.CharField(
                        choices=[
                            ("dean", "Декан"),
                            ("vice_dean", "Заместитель декана"),
                            ("head_of_department", "Заведующий кафедрой"),
                        ],
                        max_length=20,
                        verbose_name="Должность",
                    ),
                ),
                (
                    "academic_degree",
                    models.CharField(
                        choices=[
                            ("none", "Нет"),
                            ("candidate", "Кандидат наук"),
                            ("doctor", "Доктор наук"),
                        ],
                        max_length=20,
                        verbose_name="Ученая степень",
                    ),
                ),
                (
                    "academic_title",
                    models.CharField(
                        choices=[
                            ("none", "Нет"),
                            ("docent", "Доцент"),
                            ("professor", "Профессор"),
                        ],
                        max_length=20,
                        verbose_name="Ученое звание",
                    ),
                ),
                ("appointment_date", models.DateField(verbose_name="Дата назначения")),
                (
                    "term_end_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Дата окончания срока"
                    ),
                ),
                (
                    "has_teaching_duties",
                    models.BooleanField(
                        default=True,
                        verbose_name="Ведет преподавательскую деятельность",
                    ),
                ),
            ],
            options={
                "verbose_name": "профиль декана/заведующего",
                "verbose_name_plural": "профили деканов/заведующих",
            },
        ),
        migrations.CreateModel(
            name="MethodistProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "employee_id",
                    models.CharField(
                        max_length=20, unique=True, verbose_name="Табельный номер"
                    ),
                ),
                ("responsibilities", models.TextField(verbose_name="Обязанности")),
            ],
            options={
                "verbose_name": "профиль методиста",
                "verbose_name_plural": "профили методистов",
            },
        ),
        migrations.CreateModel(
            name="StudentProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "student_id",
                    models.CharField(
                        max_length=20, unique=True, verbose_name="Номер студенческого"
                    ),
                ),
                (
                    "enrollment_year",
                    models.IntegerField(verbose_name="Год поступления"),
                ),
                (
                    "education_form",
                    models.CharField(
                        choices=[
                            ("full_time", "Очная"),
                            ("part_time", "Заочная"),
                            ("evening", "Вечерняя"),
                            ("distance", "Дистанционная"),
                        ],
                        max_length=20,
                        verbose_name="Форма обучения",
                    ),
                ),
                (
                    "education_basis",
                    models.CharField(
                        choices=[
                            ("budget", "Бюджет"),
                            ("contract", "Контракт"),
                            ("targeted", "Целевое обучение"),
                        ],
                        max_length=20,
                        verbose_name="Основа обучения",
                    ),
                ),
                (
                    "current_semester",
                    models.IntegerField(verbose_name="Текущий семестр"),
                ),
                (
                    "academic_status",
                    models.CharField(
                        choices=[
                            ("active", "Учится"),
                            ("academic_leave", "Академический отпуск"),
                            ("expelled", "Отчислен"),
                            ("graduated", "Выпускник"),
                            ("sabbatical", "Академический отпуск"),
                        ],
                        default="active",
                        max_length=20,
                        verbose_name="Академический статус",
                    ),
                ),
                (
                    "scholarship_status",
                    models.CharField(
                        choices=[
                            ("none", "Нет"),
                            ("regular", "Обычная"),
                            ("elevated", "Повышенная"),
                            ("special", "Именная"),
                        ],
                        default="none",
                        max_length=20,
                        verbose_name="Статус стипендии",
                    ),
                ),
                (
                    "has_dormitory",
                    models.BooleanField(
                        default=False, verbose_name="Проживает в общежитии"
                    ),
                ),
                (
                    "personal_info",
                    models.TextField(
                        blank=True, verbose_name="Дополнительная информация"
                    ),
                ),
            ],
            options={
                "verbose_name": "профиль студента",
                "verbose_name_plural": "профили студентов",
            },
        ),
        migrations.CreateModel(
            name="TeacherProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "employee_id",
                    models.CharField(
                        max_length=20, unique=True, verbose_name="Табельный номер"
                    ),
                ),
                (
                    "position",
                    models.CharField(
                        choices=[
                            ("assistant", "Ассистент"),
                            ("lecturer", "Преподаватель"),
                            ("senior_lecturer", "Старший преподаватель"),
                            ("docent", "Доцент"),
                            ("professor", "Профессор"),
                            ("head_of_department", "Заведующий кафедрой"),
                        ],
                        max_length=50,
                        verbose_name="Должность",
                    ),
                ),
                (
                    "academic_degree",
                    models.CharField(
                        choices=[
                            ("none", "Нет"),
                            ("candidate", "Кандидат наук"),
                            ("doctor", "Доктор наук"),
                        ],
                        default="none",
                        max_length=20,
                        verbose_name="Ученая степень",
                    ),
                ),
                (
                    "academic_title",
                    models.CharField(
                        choices=[
                            ("none", "Нет"),
                            ("docent", "Доцент"),
                            ("professor", "Профессор"),
                        ],
                        default="none",
                        max_length=20,
                        verbose_name="Ученое звание",
                    ),
                ),
                (
                    "employment_type",
                    models.CharField(
                        choices=[
                            ("full_time", "Штатный"),
                            ("part_time", "Совместитель"),
                            ("contract", "Договор ГПХ"),
                        ],
                        default="full_time",
                        max_length=20,
                        verbose_name="Тип занятости",
                    ),
                ),
                (
                    "specialization",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Специализация"
                    ),
                ),
                ("hire_date", models.DateField(verbose_name="Дата приема на работу")),
                (
                    "office_location",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        verbose_name="Местоположение кабинета",
                    ),
                ),
                (
                    "office_hours",
                    models.TextField(blank=True, verbose_name="Часы консультаций"),
                ),
                ("bio", models.TextField(blank=True, verbose_name="Биография")),
            ],
            options={
                "verbose_name": "профиль преподавателя",
                "verbose_name_plural": "профили преподавателей",
            },
        ),
        migrations.CreateModel(
            name="TeacherSubject",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "academic_year",
                    models.CharField(max_length=9, verbose_name="Учебный год"),
                ),
                ("semester", models.IntegerField(verbose_name="Семестр")),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("lecturer", "Лектор"),
                            ("seminar", "Ведущий семинаров"),
                            ("lab", "Ведущий лабораторных"),
                            ("practice", "Ведущий практик"),
                            ("all", "Все виды занятий"),
                        ],
                        max_length=20,
                        verbose_name="Роль",
                    ),
                ),
            ],
            options={
                "verbose_name": "назначение преподавателя",
                "verbose_name_plural": "назначения преподавателей",
            },
        ),
        migrations.CreateModel(
            name="UserSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "session_key",
                    models.CharField(max_length=40, verbose_name="Ключ сессии"),
                ),
                ("ip_address", models.GenericIPAddressField(verbose_name="IP адрес")),
                ("user_agent", models.TextField(verbose_name="User Agent")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                ("expired_at", models.DateTimeField(verbose_name="Дата истечения")),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Активна"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sessions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "сессия пользователя",
                "verbose_name_plural": "сессии пользователей",
            },
        ),
        migrations.CreateModel(
            name="UserNotificationSetting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "email_notifications",
                    models.BooleanField(default=True, verbose_name="Email уведомления"),
                ),
                (
                    "sms_notifications",
                    models.BooleanField(default=False, verbose_name="SMS уведомления"),
                ),
                (
                    "web_notifications",
                    models.BooleanField(default=True, verbose_name="Веб уведомления"),
                ),
                (
                    "grades_notification",
                    models.BooleanField(
                        default=True, verbose_name="Уведомления об оценках"
                    ),
                ),
                (
                    "schedule_changes",
                    models.BooleanField(
                        default=True, verbose_name="Изменения расписания"
                    ),
                ),
                (
                    "course_updates",
                    models.BooleanField(default=True, verbose_name="Обновления курсов"),
                ),
                (
                    "system_messages",
                    models.BooleanField(
                        default=True, verbose_name="Системные сообщения"
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notification_settings",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "настройка уведомлений",
                "verbose_name_plural": "настройки уведомлений",
            },
        ),
    ]
