# Generated by Django 4.2.10 on 2025-05-05 21:53

import courses.models
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("accounts", "0003_teachersubject_subject_teachersubject_teacher_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Course",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="Название")),
                (
                    "slug",
                    models.SlugField(
                        blank=True,
                        max_length=255,
                        unique=True,
                        verbose_name="Идентификатор URL",
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="Описание")),
                (
                    "short_description",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Краткое описание"
                    ),
                ),
                (
                    "icon",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=courses.models.get_course_icon_path,
                        verbose_name="Иконка",
                    ),
                ),
                (
                    "cover_image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="course_covers/",
                        verbose_name="Обложка",
                    ),
                ),
                (
                    "is_published",
                    models.BooleanField(default=False, verbose_name="Опубликован"),
                ),
                (
                    "is_public",
                    models.BooleanField(default=False, verbose_name="Публичный"),
                ),
                (
                    "requires_enrollment",
                    models.BooleanField(default=True, verbose_name="Требуется запись"),
                ),
                (
                    "start_date",
                    models.DateField(blank=True, null=True, verbose_name="Дата начала"),
                ),
                (
                    "end_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Дата окончания"
                    ),
                ),
                (
                    "sequential_progression",
                    models.BooleanField(
                        default=True, verbose_name="Последовательное прохождение"
                    ),
                ),
                (
                    "completion_threshold",
                    models.PositiveSmallIntegerField(
                        default=80,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                        verbose_name="Порог завершения (%)",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
                ),
                (
                    "provides_certificate",
                    models.BooleanField(
                        default=False, verbose_name="Выдает сертификат"
                    ),
                ),
                (
                    "certificate_template",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="certificate_templates/",
                        verbose_name="Шаблон сертификата",
                    ),
                ),
            ],
            options={
                "verbose_name": "курс",
                "verbose_name_plural": "курсы",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="CourseCertificate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "certificate_number",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="Номер сертификата"
                    ),
                ),
                (
                    "issued_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Дата выдачи"),
                ),
                (
                    "certificate_file",
                    models.FileField(
                        upload_to="certificates/", verbose_name="Файл сертификата"
                    ),
                ),
                (
                    "expiration_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Дата окончания действия"
                    ),
                ),
                (
                    "additional_info",
                    models.TextField(
                        blank=True, verbose_name="Дополнительная информация"
                    ),
                ),
            ],
            options={
                "verbose_name": "сертификат курса",
                "verbose_name_plural": "сертификаты курса",
            },
        ),
        migrations.CreateModel(
            name="CourseElement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="Название")),
                ("description", models.TextField(blank=True, verbose_name="Описание")),
                ("content", models.TextField(blank=True, verbose_name="Содержимое")),
                (
                    "content_format",
                    models.CharField(
                        choices=[
                            ("plain", "Простой текст"),
                            ("markdown", "Markdown"),
                            ("html", "HTML"),
                        ],
                        default="markdown",
                        max_length=20,
                        verbose_name="Формат содержимого",
                    ),
                ),
                (
                    "order",
                    models.PositiveSmallIntegerField(default=0, verbose_name="Порядок"),
                ),
                (
                    "estimated_time",
                    models.PositiveSmallIntegerField(
                        default=0, verbose_name="Ориентировочное время (мин)"
                    ),
                ),
                (
                    "is_published",
                    models.BooleanField(default=True, verbose_name="Опубликован"),
                ),
                (
                    "is_visible",
                    models.BooleanField(
                        default=True, verbose_name="Видимый для студентов"
                    ),
                ),
                (
                    "unlock_date",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Дата открытия"
                    ),
                ),
                (
                    "is_required",
                    models.BooleanField(
                        default=True, verbose_name="Обязательный элемент"
                    ),
                ),
                (
                    "requires_previous_element",
                    models.BooleanField(
                        default=False,
                        verbose_name="Требуется завершение предыдущего элемента",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
                ),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="elements",
                        to="courses.course",
                        verbose_name="Курс",
                    ),
                ),
            ],
            options={
                "verbose_name": "элемент курса",
                "verbose_name_plural": "элементы курса",
                "ordering": ["course", "section", "order"],
            },
        ),
        migrations.CreateModel(
            name="CourseElementType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Название")),
                (
                    "code",
                    models.CharField(max_length=50, unique=True, verbose_name="Код"),
                ),
                ("description", models.TextField(blank=True, verbose_name="Описание")),
                (
                    "icon",
                    models.CharField(blank=True, max_length=50, verbose_name="Иконка"),
                ),
                (
                    "color",
                    models.CharField(
                        default="#3498db", max_length=20, verbose_name="Цвет"
                    ),
                ),
                (
                    "is_gradable",
                    models.BooleanField(default=False, verbose_name="Оцениваемый"),
                ),
                (
                    "max_score",
                    models.PositiveSmallIntegerField(
                        default=0, verbose_name="Максимальный балл"
                    ),
                ),
            ],
            options={
                "verbose_name": "тип элемента курса",
                "verbose_name_plural": "типы элементов курса",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="CourseSection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="Название")),
                ("description", models.TextField(blank=True, verbose_name="Описание")),
                (
                    "order",
                    models.PositiveSmallIntegerField(default=0, verbose_name="Порядок"),
                ),
                (
                    "is_published",
                    models.BooleanField(default=True, verbose_name="Опубликован"),
                ),
                (
                    "is_visible",
                    models.BooleanField(
                        default=True, verbose_name="Видимый для студентов"
                    ),
                ),
                (
                    "unlock_date",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Дата открытия"
                    ),
                ),
                (
                    "requires_previous_section",
                    models.BooleanField(
                        default=False,
                        verbose_name="Требуется завершение предыдущего раздела",
                    ),
                ),
                (
                    "completion_threshold",
                    models.PositiveSmallIntegerField(
                        default=100,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                        verbose_name="Порог завершения (%)",
                    ),
                ),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sections",
                        to="courses.course",
                        verbose_name="Курс",
                    ),
                ),
            ],
            options={
                "verbose_name": "раздел курса",
                "verbose_name_plural": "разделы курса",
                "ordering": ["course", "order"],
            },
        ),
        migrations.CreateModel(
            name="CourseReview",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "rating",
                    models.PositiveSmallIntegerField(
                        validators=[django.core.validators.MaxValueValidator(5)],
                        verbose_name="Оценка",
                    ),
                ),
                ("text", models.TextField(blank=True, verbose_name="Текст отзыва")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
                ),
                (
                    "is_published",
                    models.BooleanField(default=True, verbose_name="Опубликован"),
                ),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reviews",
                        to="courses.course",
                        verbose_name="Курс",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="course_reviews",
                        to="accounts.studentprofile",
                        verbose_name="Студент",
                    ),
                ),
            ],
            options={
                "verbose_name": "отзыв о курсе",
                "verbose_name_plural": "отзывы о курсе",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="CourseEnrollment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Ожидает подтверждения"),
                            ("active", "Активна"),
                            ("completed", "Завершена"),
                            ("dropped", "Отчислен"),
                            ("suspended", "Приостановлена"),
                        ],
                        default="active",
                        max_length=20,
                        verbose_name="Статус записи",
                    ),
                ),
                (
                    "progress",
                    models.PositiveSmallIntegerField(
                        default=0,
                        validators=[django.core.validators.MaxValueValidator(100)],
                        verbose_name="Прогресс (%)",
                    ),
                ),
                (
                    "last_accessed",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Последний доступ"
                    ),
                ),
                (
                    "enrolled_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Дата записи"),
                ),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Дата завершения"
                    ),
                ),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="enrollments",
                        to="courses.course",
                        verbose_name="Курс",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="course_enrollments",
                        to="accounts.studentprofile",
                        verbose_name="Студент",
                    ),
                ),
            ],
            options={
                "verbose_name": "запись на курс",
                "verbose_name_plural": "записи на курс",
            },
        ),
        migrations.CreateModel(
            name="CourseElementProgress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_viewed",
                    models.BooleanField(default=False, verbose_name="Просмотрено"),
                ),
                (
                    "is_completed",
                    models.BooleanField(default=False, verbose_name="Завершено"),
                ),
                (
                    "first_viewed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Первый просмотр"
                    ),
                ),
                (
                    "last_viewed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Последний просмотр"
                    ),
                ),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Дата завершения"
                    ),
                ),
                (
                    "time_spent",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Затраченное время (сек)"
                    ),
                ),
                (
                    "grade",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                        verbose_name="Оценка",
                    ),
                ),
                (
                    "grade_percent",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        null=True,
                        validators=[django.core.validators.MaxValueValidator(100)],
                        verbose_name="Оценка (%)",
                    ),
                ),
                (
                    "graded_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Дата оценки"
                    ),
                ),
                (
                    "feedback",
                    models.TextField(blank=True, verbose_name="Отзыв/комментарий"),
                ),
                (
                    "course_element",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="student_progress",
                        to="courses.courseelement",
                        verbose_name="Элемент курса",
                    ),
                ),
                (
                    "enrollment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="element_progress",
                        to="courses.courseenrollment",
                        verbose_name="Запись на курс",
                    ),
                ),
                (
                    "graded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="graded_elements",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Оценил",
                    ),
                ),
            ],
            options={
                "verbose_name": "прогресс по элементу курса",
                "verbose_name_plural": "прогресс по элементам курса",
            },
        ),
        migrations.CreateModel(
            name="CourseElementAttachment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="Название")),
                ("description", models.TextField(blank=True, verbose_name="Описание")),
                (
                    "file",
                    models.FileField(
                        upload_to=courses.models.get_course_material_path,
                        verbose_name="Файл",
                    ),
                ),
                (
                    "file_size",
                    models.PositiveIntegerField(default=0, verbose_name="Размер файла"),
                ),
                (
                    "file_type",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Тип файла"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "course_element",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attachments",
                        to="courses.courseelement",
                        verbose_name="Элемент курса",
                    ),
                ),
            ],
            options={
                "verbose_name": "вложение элемента курса",
                "verbose_name_plural": "вложения элементов курса",
            },
        ),
        migrations.AddField(
            model_name="courseelement",
            name="element_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="elements",
                to="courses.courseelementtype",
                verbose_name="Тип элемента",
            ),
        ),
    ]
