# Generated by Django 4.2.10 on 2025-05-05 21:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("courses", "0001_initial"),
        ("university_structure", "0001_initial"),
        ("schedule", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="courseelement",
            name="scheduled_class",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="course_elements",
                to="schedule.class",
                verbose_name="Связанное занятие",
            ),
        ),
        migrations.AddField(
            model_name="courseelement",
            name="section",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="elements",
                to="courses.coursesection",
                verbose_name="Раздел",
            ),
        ),
        migrations.AddField(
            model_name="coursecertificate",
            name="enrollment",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="certificate",
                to="courses.courseenrollment",
                verbose_name="Запись на курс",
            ),
        ),
        migrations.AddField(
            model_name="coursecertificate",
            name="signed_by",
            field=models.ManyToManyField(
                blank=True,
                related_name="signed_certificates",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Подписано",
            ),
        ),
        migrations.AddField(
            model_name="course",
            name="academic_plan_subject",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="courses",
                to="university_structure.academicplansubject",
                verbose_name="Предмет учебного плана",
            ),
        ),
        migrations.AddField(
            model_name="course",
            name="author",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="authored_courses",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Автор",
            ),
        ),
        migrations.AddField(
            model_name="course",
            name="co_authors",
            field=models.ManyToManyField(
                blank=True,
                related_name="co_authored_courses",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Соавторы",
            ),
        ),
        migrations.AddField(
            model_name="course",
            name="groups",
            field=models.ManyToManyField(
                blank=True,
                related_name="assigned_courses",
                to="university_structure.group",
                verbose_name="Группы",
            ),
        ),
        migrations.AddField(
            model_name="course",
            name="subject",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="courses",
                to="university_structure.subject",
                verbose_name="Предмет",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="coursesection",
            unique_together={("course", "order")},
        ),
        migrations.AlterUniqueTogether(
            name="coursereview",
            unique_together={("course", "student")},
        ),
        migrations.AlterUniqueTogether(
            name="courseenrollment",
            unique_together={("course", "student")},
        ),
        migrations.AlterUniqueTogether(
            name="courseelementprogress",
            unique_together={("enrollment", "course_element")},
        ),
    ]
