# Generated by Django 4.2.10 on 2025-05-05 21:53

from decimal import Decimal
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AcademicDebt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "debt_type",
                    models.CharField(
                        choices=[
                            ("exam", "Экзамен"),
                            ("credit", "Зачет"),
                            ("course_work", "Курсовая работа"),
                            ("practice", "Практика"),
                            ("attendance", "Посещаемость"),
                            ("other", "Другое"),
                        ],
                        max_length=20,
                        verbose_name="Тип задолженности",
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="Описание")),
                ("deadline", models.DateField(verbose_name="Срок погашения")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Активна"),
                            ("extended", "Продлена"),
                            ("cleared", "Погашена"),
                            ("expired", "Просрочена"),
                            ("waived", "Аннулирована"),
                        ],
                        default="active",
                        max_length=20,
                        verbose_name="Статус",
                    ),
                ),
                (
                    "cleared_at",
                    models.DateField(
                        blank=True, null=True, verbose_name="Дата погашения"
                    ),
                ),
            ],
            options={
                "verbose_name": "академическая задолженность",
                "verbose_name_plural": "академические задолженности",
                "ordering": ["student", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="AcademicPerformanceSummary",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "period_type",
                    models.CharField(
                        choices=[
                            ("semester", "Семестр"),
                            ("academic_year", "Учебный год"),
                            ("all_time", "За все время"),
                        ],
                        max_length=20,
                        verbose_name="Тип периода",
                    ),
                ),
                (
                    "total_subjects",
                    models.PositiveSmallIntegerField(
                        default=0, verbose_name="Всего предметов"
                    ),
                ),
                (
                    "excellent_count",
                    models.PositiveSmallIntegerField(default=0, verbose_name="Отлично"),
                ),
                (
                    "good_count",
                    models.PositiveSmallIntegerField(default=0, verbose_name="Хорошо"),
                ),
                (
                    "satisfactory_count",
                    models.PositiveSmallIntegerField(
                        default=0, verbose_name="Удовлетворительно"
                    ),
                ),
                (
                    "failed_count",
                    models.PositiveSmallIntegerField(
                        default=0, verbose_name="Неудовлетворительно"
                    ),
                ),
                (
                    "gpa",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=5,
                        verbose_name="Средний балл",
                    ),
                ),
                (
                    "total_credits",
                    models.PositiveSmallIntegerField(
                        default=0, verbose_name="Всего зачетных единиц"
                    ),
                ),
                (
                    "earned_credits",
                    models.PositiveSmallIntegerField(
                        default=0, verbose_name="Заработано зачетных единиц"
                    ),
                ),
                (
                    "total_classes",
                    models.PositiveSmallIntegerField(
                        default=0, verbose_name="Всего занятий"
                    ),
                ),
                (
                    "attended_classes",
                    models.PositiveSmallIntegerField(
                        default=0, verbose_name="Посещено занятий"
                    ),
                ),
                (
                    "attendance_percentage",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=5,
                        verbose_name="Процент посещаемости",
                    ),
                ),
                (
                    "ranking",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="Рейтинг в группе"
                    ),
                ),
                (
                    "group_size",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="Размер группы"
                    ),
                ),
                (
                    "calculated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Дата расчета"),
                ),
            ],
            options={
                "verbose_name": "сводка успеваемости",
                "verbose_name_plural": "сводки успеваемости",
                "ordering": ["student", "-semester"],
            },
        ),
        migrations.CreateModel(
            name="AcademicStanding",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status_type",
                    models.CharField(
                        choices=[
                            ("good", "Хорошая успеваемость"),
                            ("warning", "Предупреждение"),
                            ("probation", "Испытательный срок"),
                            ("academic_leave", "Академический отпуск"),
                            ("risk_expulsion", "Риск отчисления"),
                            ("expulsion", "Отчисление"),
                            ("reinstated", "Восстановлен"),
                            ("graduated", "Выпускник"),
                            ("transferred", "Переведен"),
                        ],
                        max_length=20,
                        verbose_name="Тип статуса",
                    ),
                ),
                (
                    "start_date",
                    models.DateField(
                        default=django.utils.timezone.now, verbose_name="Дата начала"
                    ),
                ),
                (
                    "end_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Дата окончания"
                    ),
                ),
                ("reason", models.TextField(blank=True, verbose_name="Причина")),
                (
                    "document_number",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Номер документа"
                    ),
                ),
                (
                    "document_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Дата документа"
                    ),
                ),
                ("comments", models.TextField(blank=True, verbose_name="Комментарии")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
                ),
            ],
            options={
                "verbose_name": "академический статус",
                "verbose_name_plural": "академические статусы",
                "ordering": ["student", "-start_date"],
            },
        ),
        migrations.CreateModel(
            name="Attendance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("present", "Присутствовал"),
                            ("absent", "Отсутствовал"),
                            ("late", "Опоздал"),
                            ("sick", "Болен"),
                            ("excused", "Уважительная причина"),
                        ],
                        max_length=20,
                        verbose_name="Статус",
                    ),
                ),
                (
                    "late_minutes",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="Опоздание (мин)"
                    ),
                ),
                ("reason", models.TextField(blank=True, verbose_name="Причина")),
                (
                    "marked_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата отметки"
                    ),
                ),
            ],
            options={
                "verbose_name": "посещаемость",
                "verbose_name_plural": "посещаемость",
            },
        ),
        migrations.CreateModel(
            name="AttendanceSheet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("not_filled", "Не заполнен"),
                            ("partially_filled", "Частично заполнен"),
                            ("filled", "Заполнен"),
                            ("verified", "Проверен"),
                        ],
                        default="not_filled",
                        max_length=20,
                        verbose_name="Статус",
                    ),
                ),
                ("comments", models.TextField(blank=True, verbose_name="Комментарии")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
                ),
            ],
            options={
                "verbose_name": "журнал посещаемости",
                "verbose_name_plural": "журналы посещаемости",
            },
        ),
        migrations.CreateModel(
            name="Grade",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "points",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="Баллы",
                    ),
                ),
                (
                    "max_points",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="Максимум баллов",
                    ),
                ),
                (
                    "percentage",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                        verbose_name="Процент",
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("manual", "Ручной ввод"),
                            ("auto", "Автоматически"),
                            ("imported", "Импортировано"),
                            ("calculated", "Вычислено"),
                        ],
                        default="manual",
                        max_length=20,
                        verbose_name="Источник",
                    ),
                ),
                ("comments", models.TextField(blank=True, verbose_name="Комментарии")),
                (
                    "date",
                    models.DateField(
                        default=django.utils.timezone.now, verbose_name="Дата"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Черновик"),
                            ("final", "Окончательная"),
                            ("corrected", "Исправленная"),
                            ("annulled", "Аннулированная"),
                        ],
                        default="final",
                        max_length=20,
                        verbose_name="Статус",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
                ),
            ],
            options={
                "verbose_name": "оценка",
                "verbose_name_plural": "оценки",
                "ordering": ["-date", "student"],
            },
        ),
        migrations.CreateModel(
            name="GradeConversion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
            options={
                "verbose_name": "соответствие оценок",
                "verbose_name_plural": "соответствия оценок",
            },
        ),
        migrations.CreateModel(
            name="GradeExport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "format",
                    models.CharField(
                        choices=[
                            ("csv", "CSV"),
                            ("excel", "Excel"),
                            ("pdf", "PDF"),
                            ("json", "JSON"),
                            ("xml", "XML"),
                        ],
                        max_length=10,
                        verbose_name="Формат",
                    ),
                ),
                (
                    "include_attendance",
                    models.BooleanField(
                        default=False, verbose_name="Включить посещаемость"
                    ),
                ),
                (
                    "include_comments",
                    models.BooleanField(
                        default=False, verbose_name="Включить комментарии"
                    ),
                ),
                (
                    "export_date",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата экспорта"
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="grade_exports/",
                        verbose_name="Файл",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "В процессе"),
                            ("completed", "Завершен"),
                            ("failed", "Ошибка"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="Статус",
                    ),
                ),
                (
                    "records_count",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Количество записей"
                    ),
                ),
            ],
            options={
                "verbose_name": "экспорт оценок",
                "verbose_name_plural": "экспорты оценок",
                "ordering": ["-export_date"],
            },
        ),
        migrations.CreateModel(
            name="GradeHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "changed_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата изменения"
                    ),
                ),
                (
                    "change_type",
                    models.CharField(
                        choices=[
                            ("create", "Создание"),
                            ("update", "Изменение"),
                            ("delete", "Удаление"),
                        ],
                        max_length=20,
                        verbose_name="Тип изменения",
                    ),
                ),
                ("comments", models.TextField(blank=True, verbose_name="Комментарии")),
            ],
            options={
                "verbose_name": "история оценок",
                "verbose_name_plural": "история оценок",
                "ordering": ["-changed_at"],
            },
        ),
        migrations.CreateModel(
            name="GradeImport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("csv", "CSV файл"),
                            ("excel", "Excel файл"),
                            ("api", "Внешний API"),
                            ("manual", "Ручной ввод"),
                            ("other", "Другое"),
                        ],
                        max_length=20,
                        verbose_name="Источник",
                    ),
                ),
                (
                    "filename",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Имя файла"
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="grade_imports/",
                        verbose_name="Файл",
                    ),
                ),
                (
                    "import_date",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата импорта"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Ожидает обработки"),
                            ("processing", "Обрабатывается"),
                            ("completed", "Завершен"),
                            ("failed", "Ошибка"),
                            ("partially_completed", "Частично завершен"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="Статус",
                    ),
                ),
                (
                    "total_records",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Всего записей"
                    ),
                ),
                (
                    "processed_records",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Обработано записей"
                    ),
                ),
                (
                    "successful_records",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Успешно импортировано"
                    ),
                ),
                (
                    "failed_records",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Ошибки импорта"
                    ),
                ),
                (
                    "error_log",
                    models.TextField(blank=True, verbose_name="Журнал ошибок"),
                ),
            ],
            options={
                "verbose_name": "импорт оценок",
                "verbose_name_plural": "импорты оценок",
                "ordering": ["-import_date"],
            },
        ),
        migrations.CreateModel(
            name="GradeImportItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "student_id",
                    models.CharField(max_length=50, verbose_name="ID студента"),
                ),
                (
                    "subject_code",
                    models.CharField(max_length=50, verbose_name="Код предмета"),
                ),
                (
                    "semester_id",
                    models.CharField(max_length=50, verbose_name="ID семестра"),
                ),
                (
                    "grade_value",
                    models.CharField(max_length=20, verbose_name="Значение оценки"),
                ),
                (
                    "grade_type",
                    models.CharField(max_length=50, verbose_name="Тип оценки"),
                ),
                (
                    "grade_date",
                    models.DateField(blank=True, null=True, verbose_name="Дата оценки"),
                ),
                (
                    "additional_data",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="Дополнительные данные"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Ожидает обработки"),
                            ("processed", "Обработана"),
                            ("error", "Ошибка"),
                            ("skipped", "Пропущена"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="Статус",
                    ),
                ),
                (
                    "error_message",
                    models.TextField(blank=True, verbose_name="Сообщение об ошибке"),
                ),
            ],
            options={
                "verbose_name": "запись импорта оценки",
                "verbose_name_plural": "записи импорта оценок",
            },
        ),
        migrations.CreateModel(
            name="GradeSheet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sheet_type",
                    models.CharField(
                        choices=[
                            ("exam", "Экзаменационная"),
                            ("credit", "Зачетная"),
                            ("credit_grade", "Дифференцированный зачет"),
                            ("course_work", "Курсовая работа"),
                            ("practice", "Практика"),
                            ("final", "Итоговая"),
                        ],
                        max_length=20,
                        verbose_name="Тип ведомости",
                    ),
                ),
                (
                    "number",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="Номер ведомости"
                    ),
                ),
                (
                    "issue_date",
                    models.DateField(
                        default=django.utils.timezone.now, verbose_name="Дата выдачи"
                    ),
                ),
                (
                    "expiration_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Срок действия до"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Черновик"),
                            ("issued", "Выдана"),
                            ("in_progress", "В процессе заполнения"),
                            ("completed", "Заполнена"),
                            ("verified", "Проверена"),
                            ("approved", "Утверждена"),
                            ("archived", "В архиве"),
                        ],
                        default="draft",
                        max_length=20,
                        verbose_name="Статус",
                    ),
                ),
                ("comments", models.TextField(blank=True, verbose_name="Комментарии")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
                ),
            ],
            options={
                "verbose_name": "ведомость оценок",
                "verbose_name_plural": "ведомости оценок",
                "ordering": ["-issue_date", "group"],
            },
        ),
        migrations.CreateModel(
            name="GradeSheetItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "points",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="Баллы",
                    ),
                ),
                (
                    "percentage",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                        verbose_name="Процент",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("not_graded", "Не оценено"),
                            ("graded", "Оценено"),
                            ("absent", "Не явился"),
                            ("not_allowed", "Не допущен"),
                        ],
                        default="not_graded",
                        max_length=20,
                        verbose_name="Статус",
                    ),
                ),
                (
                    "graded_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Дата оценки"
                    ),
                ),
                ("comments", models.TextField(blank=True, verbose_name="Комментарии")),
            ],
            options={
                "verbose_name": "запись в ведомости",
                "verbose_name_plural": "записи в ведомости",
                "ordering": ["grade_sheet", "student"],
            },
        ),
        migrations.CreateModel(
            name="GradeSystem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Название")),
                ("description", models.TextField(blank=True, verbose_name="Описание")),
                (
                    "min_value",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=5,
                        verbose_name="Минимальное значение",
                    ),
                ),
                (
                    "max_value",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("100.00"),
                        max_digits=5,
                        verbose_name="Максимальное значение",
                    ),
                ),
                (
                    "passing_value",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("60.00"),
                        max_digits=5,
                        verbose_name="Проходной балл",
                    ),
                ),
                (
                    "system_type",
                    models.CharField(
                        choices=[
                            ("numeric", "Числовая (от min до max)"),
                            ("letter", "Буквенная (A, B, C...)"),
                            ("pass_fail", "Зачет/Незачет"),
                            ("custom", "Пользовательская"),
                        ],
                        max_length=20,
                        verbose_name="Тип системы",
                    ),
                ),
                (
                    "rounding_method",
                    models.CharField(
                        choices=[
                            ("none", "Не округлять"),
                            ("ceil", "К большему"),
                            ("floor", "К меньшему"),
                            ("round", "Математическое"),
                        ],
                        default="round",
                        max_length=10,
                        verbose_name="Метод округления",
                    ),
                ),
                (
                    "decimal_places",
                    models.PositiveSmallIntegerField(
                        default=2, verbose_name="Знаков после запятой"
                    ),
                ),
                (
                    "is_default",
                    models.BooleanField(default=False, verbose_name="По умолчанию"),
                ),
            ],
            options={
                "verbose_name": "система оценивания",
                "verbose_name_plural": "системы оценивания",
            },
        ),
        migrations.CreateModel(
            name="GradeType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Название")),
                (
                    "code",
                    models.CharField(max_length=20, unique=True, verbose_name="Код"),
                ),
                ("description", models.TextField(blank=True, verbose_name="Описание")),
                (
                    "weight_in_final",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("1.00"),
                        max_digits=5,
                        verbose_name="Вес в итоговой оценке",
                    ),
                ),
            ],
            options={
                "verbose_name": "тип оценки",
                "verbose_name_plural": "типы оценок",
            },
        ),
        migrations.CreateModel(
            name="GradeValue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("value", models.CharField(max_length=10, verbose_name="Значение")),
                (
                    "numeric_value",
                    models.DecimalField(
                        decimal_places=2, max_digits=5, verbose_name="Числовое значение"
                    ),
                ),
                (
                    "min_percent",
                    models.DecimalField(
                        decimal_places=2, max_digits=5, verbose_name="От (%)"
                    ),
                ),
                (
                    "max_percent",
                    models.DecimalField(
                        decimal_places=2, max_digits=5, verbose_name="До (%)"
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Описание"
                    ),
                ),
                (
                    "is_passing",
                    models.BooleanField(default=True, verbose_name="Проходная оценка"),
                ),
            ],
            options={
                "verbose_name": "значение оценки",
                "verbose_name_plural": "значения оценок",
                "ordering": ["grade_system", "-numeric_value"],
            },
        ),
        migrations.CreateModel(
            name="GradingScale",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Название")),
                ("description", models.TextField(blank=True, verbose_name="Описание")),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Активна"),
                ),
            ],
            options={
                "verbose_name": "шкала перевода оценок",
                "verbose_name_plural": "шкалы перевода оценок",
            },
        ),
        migrations.CreateModel(
            name="IndividualPlan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start_date", models.DateField(verbose_name="Дата начала")),
                ("end_date", models.DateField(verbose_name="Дата окончания")),
                (
                    "document_number",
                    models.CharField(max_length=100, verbose_name="Номер приказа"),
                ),
                ("document_date", models.DateField(verbose_name="Дата приказа")),
                ("reason", models.TextField(verbose_name="Причина создания")),
                ("description", models.TextField(verbose_name="Описание изменений")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Черновик"),
                            ("pending_approval", "Ожидает утверждения"),
                            ("approved", "Утвержден"),
                            ("active", "Активен"),
                            ("completed", "Завершен"),
                            ("canceled", "Отменен"),
                        ],
                        default="draft",
                        max_length=20,
                        verbose_name="Статус",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
                ),
            ],
            options={
                "verbose_name": "индивидуальный учебный план",
                "verbose_name_plural": "индивидуальные учебные планы",
                "ordering": ["student", "-start_date"],
            },
        ),
        migrations.CreateModel(
            name="IndividualPlanItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "lectures_hours",
                    models.PositiveSmallIntegerField(default=0, verbose_name="Лекции"),
                ),
                (
                    "seminars_hours",
                    models.PositiveSmallIntegerField(
                        default=0, verbose_name="Семинары"
                    ),
                ),
                (
                    "labs_hours",
                    models.PositiveSmallIntegerField(
                        default=0, verbose_name="Лабораторные"
                    ),
                ),
                (
                    "practices_hours",
                    models.PositiveSmallIntegerField(
                        default=0, verbose_name="Практики"
                    ),
                ),
                (
                    "self_study_hours",
                    models.PositiveSmallIntegerField(
                        default=0, verbose_name="Самостоятельная работа"
                    ),
                ),
                (
                    "credits",
                    models.PositiveSmallIntegerField(verbose_name="Зачетные единицы"),
                ),
                (
                    "control_form",
                    models.CharField(
                        choices=[
                            ("exam", "Экзамен"),
                            ("credit", "Зачет"),
                            ("credit_grade", "Зачет с оценкой"),
                            ("coursework", "Курсовая работа"),
                            ("coursework_project", "Курсовой проект"),
                            ("practice", "Практика"),
                        ],
                        max_length=20,
                        verbose_name="Форма контроля",
                    ),
                ),
                (
                    "change_type",
                    models.CharField(
                        choices=[
                            ("replace", "Замена предмета"),
                            ("move", "Перенос в другой семестр"),
                            ("add", "Добавление предмета"),
                            ("remove", "Удаление предмета"),
                            ("modify", "Изменение параметров"),
                        ],
                        max_length=20,
                        verbose_name="Тип изменения",
                    ),
                ),
                (
                    "reason",
                    models.TextField(blank=True, verbose_name="Обоснование изменения"),
                ),
            ],
            options={
                "verbose_name": "элемент индивидуального плана",
                "verbose_name_plural": "элементы индивидуального плана",
                "ordering": ["individual_plan", "semester", "subject"],
            },
        ),
        migrations.CreateModel(
            name="RecordEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "entry_type",
                    models.CharField(
                        choices=[
                            ("exam", "Экзамен"),
                            ("credit", "Зачет"),
                            ("credit_grade", "Дифференцированный зачет"),
                            ("course_work", "Курсовая работа"),
                            ("course_project", "Курсовой проект"),
                            ("practice", "Практика"),
                            ("state_exam", "Государственный экзамен"),
                            ("vkr", "Выпускная квалификационная работа"),
                            ("other", "Другое"),
                        ],
                        max_length=20,
                        verbose_name="Тип записи",
                    ),
                ),
                (
                    "hours",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="Часы"
                    ),
                ),
                (
                    "credits",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="Зачетные единицы"
                    ),
                ),
                ("date", models.DateField(verbose_name="Дата записи")),
                ("comments", models.TextField(blank=True, verbose_name="Комментарии")),
                (
                    "title",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Название работы"
                    ),
                ),
            ],
            options={
                "verbose_name": "запись в зачетной книжке",
                "verbose_name_plural": "записи в зачетной книжке",
                "ordering": ["semester", "subject"],
            },
        ),
        migrations.CreateModel(
            name="RetakePermission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "attempt_number",
                    models.PositiveSmallIntegerField(
                        default=1, verbose_name="Номер попытки"
                    ),
                ),
                (
                    "issue_date",
                    models.DateField(
                        default=django.utils.timezone.now, verbose_name="Дата выдачи"
                    ),
                ),
                ("expiration_date", models.DateField(verbose_name="Срок действия до")),
                (
                    "document_number",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Номер документа"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("issued", "Выдано"),
                            ("used", "Использовано"),
                            ("expired", "Истекло"),
                            ("canceled", "Аннулировано"),
                        ],
                        default="issued",
                        max_length=20,
                        verbose_name="Статус",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
                ),
            ],
            options={
                "verbose_name": "разрешение на пересдачу",
                "verbose_name_plural": "разрешения на пересдачу",
                "ordering": ["student", "-issue_date", "subject"],
            },
        ),
        migrations.CreateModel(
            name="Scholarship",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Название")),
                ("description", models.TextField(blank=True, verbose_name="Описание")),
                (
                    "scholarship_type",
                    models.CharField(
                        choices=[
                            ("academic", "Академическая"),
                            ("social", "Социальная"),
                            ("named", "Именная"),
                            ("president", "Президентская"),
                            ("government", "Правительственная"),
                            ("other", "Другая"),
                        ],
                        max_length=20,
                        verbose_name="Тип стипендии",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Сумма"
                    ),
                ),
                (
                    "gpa_requirement",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                        verbose_name="Требуемый средний балл",
                    ),
                ),
                (
                    "attendance_requirement",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                        verbose_name="Требуемый процент посещаемости",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Активна"),
                ),
            ],
            options={
                "verbose_name": "стипендия",
                "verbose_name_plural": "стипендии",
            },
        ),
        migrations.CreateModel(
            name="ScholarshipAssignment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start_date", models.DateField(verbose_name="Дата начала")),
                ("end_date", models.DateField(verbose_name="Дата окончания")),
                (
                    "document_number",
                    models.CharField(max_length=100, verbose_name="Номер приказа"),
                ),
                ("document_date", models.DateField(verbose_name="Дата приказа")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Ожидает"),
                            ("active", "Активна"),
                            ("suspended", "Приостановлена"),
                            ("terminated", "Прекращена"),
                            ("completed", "Завершена"),
                        ],
                        default="active",
                        max_length=20,
                        verbose_name="Статус",
                    ),
                ),
                (
                    "status_reason",
                    models.TextField(
                        blank=True, verbose_name="Причина изменения статуса"
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="Фактическая сумма",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
                ),
            ],
            options={
                "verbose_name": "назначение стипендии",
                "verbose_name_plural": "назначения стипендий",
                "ordering": ["student", "-start_date"],
            },
        ),
        migrations.CreateModel(
            name="StudentRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "record_number",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="Номер зачетной книжки"
                    ),
                ),
                (
                    "issue_date",
                    models.DateField(
                        default=django.utils.timezone.now, verbose_name="Дата выдачи"
                    ),
                ),
                (
                    "closing_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Дата закрытия"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Активна"),
                            ("archived", "В архиве"),
                            ("lost", "Утеряна"),
                            ("closed", "Закрыта"),
                        ],
                        default="active",
                        max_length=20,
                        verbose_name="Статус",
                    ),
                ),
                ("comments", models.TextField(blank=True, verbose_name="Комментарии")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
                ),
            ],
            options={
                "verbose_name": "зачетная книжка",
                "verbose_name_plural": "зачетные книжки",
            },
        ),
    ]
