# Generated by Django 4.2.10 on 2025-05-06 21:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("site_settings", "0002_adminprofilesettings_deanprofilesettings_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProfileSection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "profile_type",
                    models.CharField(
                        choices=[
                            ("student", "Студент"),
                            ("teacher", "Преподаватель"),
                            ("admin", "Администратор"),
                            ("methodist", "Методист"),
                            ("dean", "Декан/Заведующий кафедрой"),
                        ],
                        max_length=20,
                        verbose_name="Тип профиля",
                    ),
                ),
                (
                    "section_type",
                    models.CharField(
                        choices=[
                            ("info", "Информация"),
                            ("skills", "Навыки"),
                            ("certificates", "Сертификаты"),
                            ("activity", "Активность"),
                            ("achievements", "Достижения"),
                            ("courses", "Курсы"),
                            ("publications", "Публикации"),
                            ("statistics", "Статистика"),
                        ],
                        max_length=50,
                        verbose_name="Тип раздела",
                    ),
                ),
                (
                    "is_visible",
                    models.BooleanField(default=True, verbose_name="Отображать"),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Порядок отображения"
                    ),
                ),
            ],
            options={
                "verbose_name": "раздел профиля",
                "verbose_name_plural": "разделы профиля",
                "ordering": ["profile_type", "order"],
                "unique_together": {("profile_type", "section_type")},
            },
        ),
        migrations.CreateModel(
            name="ProfileField",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "profile_type",
                    models.CharField(
                        choices=[
                            ("student", "Студент"),
                            ("teacher", "Преподаватель"),
                            ("admin", "Администратор"),
                            ("methodist", "Методист"),
                            ("dean", "Декан/Заведующий кафедрой"),
                        ],
                        max_length=20,
                        verbose_name="Тип профиля",
                    ),
                ),
                (
                    "field_name",
                    models.CharField(max_length=100, verbose_name="Имя поля"),
                ),
                (
                    "display_name",
                    models.CharField(
                        max_length=100, verbose_name="Отображаемое название"
                    ),
                ),
                (
                    "is_visible",
                    models.BooleanField(default=True, verbose_name="Отображать"),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Порядок отображения"
                    ),
                ),
                (
                    "section",
                    models.CharField(
                        choices=[
                            ("main", "Основная информация"),
                            ("additional", "Дополнительная информация"),
                            ("tabs", "Вкладки"),
                        ],
                        default="main",
                        max_length=50,
                        verbose_name="Раздел",
                    ),
                ),
            ],
            options={
                "verbose_name": "поле профиля",
                "verbose_name_plural": "поля профиля",
                "ordering": ["profile_type", "section", "order"],
                "unique_together": {("profile_type", "field_name")},
            },
        ),
    ]
