# Generated by Django 4.2.10 on 2025-05-06 21:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("site_settings", "0003_profilesection_profilefield"),
    ]

    operations = [
        migrations.CreateModel(
            name="StudentProfileDisplaySettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "show_faculty",
                    models.BooleanField(
                        default=True, verbose_name="Показывать факультет"
                    ),
                ),
                (
                    "show_specialization",
                    models.BooleanField(
                        default=True, verbose_name="Показывать направление"
                    ),
                ),
                (
                    "show_group",
                    models.BooleanField(default=True, verbose_name="Показывать группу"),
                ),
                (
                    "show_student_id",
                    models.BooleanField(
                        default=True, verbose_name="Показывать номер студенческого"
                    ),
                ),
                (
                    "show_education_form",
                    models.BooleanField(
                        default=True, verbose_name="Показывать форму обучения"
                    ),
                ),
                (
                    "show_education_basis",
                    models.BooleanField(
                        default=True, verbose_name="Показывать основу обучения"
                    ),
                ),
                (
                    "show_enrollment_year",
                    models.BooleanField(
                        default=True, verbose_name="Показывать год поступления"
                    ),
                ),
                (
                    "show_current_semester",
                    models.BooleanField(
                        default=True, verbose_name="Показывать текущий семестр"
                    ),
                ),
                (
                    "show_academic_status",
                    models.BooleanField(default=True, verbose_name="Показывать статус"),
                ),
                (
                    "show_scholarship_status",
                    models.BooleanField(
                        default=True, verbose_name="Показывать стипендию"
                    ),
                ),
                (
                    "show_dormitory",
                    models.BooleanField(
                        default=True, verbose_name="Показывать проживание в общежитии"
                    ),
                ),
                (
                    "show_personal_info",
                    models.BooleanField(
                        default=True, verbose_name="Показывать личную информацию"
                    ),
                ),
                (
                    "show_skills",
                    models.BooleanField(
                        default=True, verbose_name="Показывать раздел навыков"
                    ),
                ),
                (
                    "show_certificates",
                    models.BooleanField(
                        default=True, verbose_name="Показывать раздел сертификатов"
                    ),
                ),
                (
                    "show_achievements",
                    models.BooleanField(
                        default=True, verbose_name="Показывать раздел достижений"
                    ),
                ),
                (
                    "show_courses",
                    models.BooleanField(
                        default=True, verbose_name="Показывать раздел курсов"
                    ),
                ),
                (
                    "show_activity",
                    models.BooleanField(
                        default=True, verbose_name="Показывать раздел активности"
                    ),
                ),
                (
                    "show_statistics",
                    models.BooleanField(
                        default=True, verbose_name="Показывать раздел статистики"
                    ),
                ),
            ],
            options={
                "verbose_name": "настройки отображения профиля студента",
                "verbose_name_plural": "настройки отображения профиля студента",
            },
        ),
        migrations.CreateModel(
            name="TeacherProfileDisplaySettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "show_department",
                    models.BooleanField(
                        default=True, verbose_name="Показывать кафедру"
                    ),
                ),
                (
                    "show_position",
                    models.BooleanField(
                        default=True, verbose_name="Показывать должность"
                    ),
                ),
                (
                    "show_academic_degree",
                    models.BooleanField(
                        default=True, verbose_name="Показывать учёную степень"
                    ),
                ),
                (
                    "show_academic_title",
                    models.BooleanField(
                        default=True, verbose_name="Показывать учёное звание"
                    ),
                ),
                (
                    "show_employment_type",
                    models.BooleanField(
                        default=True, verbose_name="Показывать тип занятости"
                    ),
                ),
                (
                    "show_specialization",
                    models.BooleanField(
                        default=True, verbose_name="Показывать специализацию"
                    ),
                ),
                (
                    "show_hire_date",
                    models.BooleanField(
                        default=True, verbose_name="Показывать дату приёма на работу"
                    ),
                ),
                (
                    "show_office_location",
                    models.BooleanField(
                        default=True, verbose_name="Показывать местоположение кабинета"
                    ),
                ),
                (
                    "show_office_hours",
                    models.BooleanField(
                        default=True, verbose_name="Показывать часы консультаций"
                    ),
                ),
                (
                    "show_bio",
                    models.BooleanField(
                        default=True, verbose_name="Показывать биографию"
                    ),
                ),
                (
                    "show_courses",
                    models.BooleanField(
                        default=True, verbose_name="Показывать раздел курсов"
                    ),
                ),
                (
                    "show_publications",
                    models.BooleanField(
                        default=True, verbose_name="Показывать раздел публикаций"
                    ),
                ),
            ],
            options={
                "verbose_name": "настройки отображения профиля преподавателя",
                "verbose_name_plural": "настройки отображения профиля преподавателя",
            },
        ),
        migrations.RenameModel(
            old_name="AdminProfileSettings",
            new_name="AdminProfileDisplaySettings",
        ),
        migrations.RenameModel(
            old_name="DeanProfileSettings",
            new_name="DeanProfileDisplaySettings",
        ),
        migrations.RenameModel(
            old_name="MethodistProfileSettings",
            new_name="MethodistProfileDisplaySettings",
        ),
        migrations.DeleteModel(
            name="ProfileField",
        ),
        migrations.DeleteModel(
            name="ProfileFieldSettings",
        ),
        migrations.DeleteModel(
            name="ProfileSection",
        ),
        migrations.DeleteModel(
            name="StudentProfileSettings",
        ),
        migrations.DeleteModel(
            name="TeacherProfileSettings",
        ),
        migrations.AlterModelOptions(
            name="adminprofiledisplaysettings",
            options={
                "verbose_name": "настройки отображения профиля администратора",
                "verbose_name_plural": "настройки отображения профиля администратора",
            },
        ),
        migrations.AlterModelOptions(
            name="deanprofiledisplaysettings",
            options={
                "verbose_name": "настройки отображения профиля декана/заведующего",
                "verbose_name_plural": "настройки отображения профиля декана/заведующего",
            },
        ),
        migrations.AlterModelOptions(
            name="methodistprofiledisplaysettings",
            options={
                "verbose_name": "настройки отображения профиля методиста",
                "verbose_name_plural": "настройки отображения профиля методиста",
            },
        ),
    ]
