# Generated by Django 4.2.10 on 2025-05-05 21:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("accounts", "0002_adminprofile_deanprofile_methodistprofile_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="AcademicPlan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("year", models.CharField(max_length=9, verbose_name="Год")),
                ("approval_date", models.DateField(verbose_name="Дата утверждения")),
                (
                    "version",
                    models.CharField(
                        default="1.0", max_length=20, verbose_name="Версия"
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="Описание")),
                (
                    "file",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="academic_plans/",
                        verbose_name="Файл плана",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Активен"),
                ),
            ],
            options={
                "verbose_name": "учебный план",
                "verbose_name_plural": "учебные планы",
            },
        ),
        migrations.CreateModel(
            name="AcademicYear",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=9, verbose_name="Название")),
                ("start_date", models.DateField(verbose_name="Дата начала")),
                ("end_date", models.DateField(verbose_name="Дата окончания")),
                (
                    "is_current",
                    models.BooleanField(default=False, verbose_name="Текущий"),
                ),
            ],
            options={
                "verbose_name": "учебный год",
                "verbose_name_plural": "учебные годы",
                "ordering": ["-start_date"],
            },
        ),
        migrations.CreateModel(
            name="Building",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Название")),
                ("number", models.CharField(max_length=10, verbose_name="Номер")),
                ("address", models.CharField(max_length=255, verbose_name="Адрес")),
                ("description", models.TextField(blank=True, verbose_name="Описание")),
                (
                    "floors",
                    models.PositiveSmallIntegerField(
                        default=1, verbose_name="Количество этажей"
                    ),
                ),
                (
                    "latitude",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        max_digits=9,
                        null=True,
                        verbose_name="Широта",
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        max_digits=9,
                        null=True,
                        verbose_name="Долгота",
                    ),
                ),
            ],
            options={
                "verbose_name": "здание",
                "verbose_name_plural": "здания",
            },
        ),
        migrations.CreateModel(
            name="Department",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Название")),
                (
                    "short_name",
                    models.CharField(max_length=20, verbose_name="Сокращение"),
                ),
                (
                    "code",
                    models.CharField(max_length=20, unique=True, verbose_name="Код"),
                ),
                ("description", models.TextField(blank=True, verbose_name="Описание")),
                (
                    "foundation_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Дата основания"
                    ),
                ),
                ("website", models.URLField(blank=True, verbose_name="Веб-сайт")),
                (
                    "email",
                    models.EmailField(blank=True, max_length=254, verbose_name="Email"),
                ),
                (
                    "phone",
                    models.CharField(blank=True, max_length=20, verbose_name="Телефон"),
                ),
                (
                    "address",
                    models.CharField(blank=True, max_length=255, verbose_name="Адрес"),
                ),
                (
                    "room_number",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="Номер аудитории"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Активен"),
                ),
            ],
            options={
                "verbose_name": "кафедра",
                "verbose_name_plural": "кафедры",
                "ordering": ["faculty", "name"],
            },
        ),
        migrations.CreateModel(
            name="EducationalProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Название")),
                (
                    "code",
                    models.CharField(blank=True, max_length=30, verbose_name="Код"),
                ),
                ("description", models.TextField(blank=True, verbose_name="Описание")),
                (
                    "start_year",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Год начала"
                    ),
                ),
                (
                    "end_year",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Год окончания"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Активен"),
                ),
            ],
            options={
                "verbose_name": "профиль образовательной программы",
                "verbose_name_plural": "профили образовательных программ",
            },
        ),
        migrations.CreateModel(
            name="EducationLevel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Название")),
                (
                    "code",
                    models.CharField(max_length=20, unique=True, verbose_name="Код"),
                ),
                (
                    "study_duration",
                    models.PositiveSmallIntegerField(
                        verbose_name="Продолжительность (в годах)"
                    ),
                ),
            ],
            options={
                "verbose_name": "уровень образования",
                "verbose_name_plural": "уровни образования",
            },
        ),
        migrations.CreateModel(
            name="Faculty",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Название")),
                (
                    "short_name",
                    models.CharField(max_length=20, verbose_name="Сокращение"),
                ),
                (
                    "code",
                    models.CharField(max_length=20, unique=True, verbose_name="Код"),
                ),
                ("description", models.TextField(blank=True, verbose_name="Описание")),
                (
                    "foundation_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Дата основания"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Активен"),
                ),
            ],
            options={
                "verbose_name": "факультет",
                "verbose_name_plural": "факультеты",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Group",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, verbose_name="Название")),
                (
                    "year_of_admission",
                    models.PositiveIntegerField(verbose_name="Год набора"),
                ),
                (
                    "current_semester",
                    models.PositiveSmallIntegerField(verbose_name="Текущий семестр"),
                ),
                (
                    "education_form",
                    models.CharField(
                        choices=[
                            ("full_time", "Очная"),
                            ("part_time", "Заочная"),
                            ("evening", "Вечерняя"),
                            ("distance", "Дистанционная"),
                        ],
                        max_length=20,
                        verbose_name="Форма обучения",
                    ),
                ),
                (
                    "max_students",
                    models.PositiveSmallIntegerField(
                        default=30, verbose_name="Максимальное количество студентов"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Активна"),
                ),
                (
                    "academic_plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="groups",
                        to="university_structure.academicplan",
                    ),
                ),
                (
                    "curator",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="curated_groups",
                        to="accounts.teacherprofile",
                    ),
                ),
                (
                    "profile",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="groups",
                        to="university_structure.educationalprofile",
                    ),
                ),
            ],
            options={
                "verbose_name": "учебная группа",
                "verbose_name_plural": "учебные группы",
            },
        ),
        migrations.CreateModel(
            name="Subgroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, verbose_name="Название")),
                (
                    "subgroup_type",
                    models.CharField(
                        choices=[
                            ("general", "Общая"),
                            ("language", "Языковая"),
                            ("lab", "Лабораторная"),
                            ("elective", "По выбору"),
                        ],
                        default="general",
                        max_length=20,
                        verbose_name="Тип",
                    ),
                ),
                (
                    "max_students",
                    models.PositiveSmallIntegerField(
                        default=15, verbose_name="Максимальное количество студентов"
                    ),
                ),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subgroups",
                        to="university_structure.group",
                    ),
                ),
            ],
            options={
                "verbose_name": "подгруппа",
                "verbose_name_plural": "подгруппы",
                "unique_together": {("group", "name")},
            },
        ),
        migrations.CreateModel(
            name="Subject",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Название")),
                (
                    "short_name",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="Сокращение"
                    ),
                ),
                (
                    "code",
                    models.CharField(max_length=20, unique=True, verbose_name="Код"),
                ),
                ("description", models.TextField(blank=True, verbose_name="Описание")),
                (
                    "subject_type",
                    models.CharField(
                        choices=[
                            ("base", "Базовая часть"),
                            ("variable", "Вариативная часть"),
                            ("elective", "По выбору"),
                            ("faculty", "Факультативная"),
                        ],
                        default="base",
                        max_length=20,
                        verbose_name="Тип",
                    ),
                ),
                (
                    "department",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subjects",
                        to="university_structure.department",
                    ),
                ),
            ],
            options={
                "verbose_name": "дисциплина",
                "verbose_name_plural": "дисциплины",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Specialization",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Название")),
                ("code", models.CharField(max_length=20, verbose_name="Код")),
                (
                    "qualification",
                    models.CharField(max_length=100, verbose_name="Квалификация"),
                ),
                ("description", models.TextField(blank=True, verbose_name="Описание")),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Активна"),
                ),
                (
                    "department",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="specializations",
                        to="university_structure.department",
                    ),
                ),
                (
                    "education_level",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="specializations",
                        to="university_structure.educationlevel",
                    ),
                ),
            ],
            options={
                "verbose_name": "направление подготовки",
                "verbose_name_plural": "направления подготовки",
                "unique_together": {("code", "education_level")},
            },
        ),
        migrations.CreateModel(
            name="Room",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("number", models.CharField(max_length=20, verbose_name="Номер")),
                ("floor", models.PositiveSmallIntegerField(verbose_name="Этаж")),
                (
                    "room_type",
                    models.CharField(
                        choices=[
                            ("lecture", "Лекционная"),
                            ("seminar", "Семинарская"),
                            ("lab", "Лаборатория"),
                            ("computer", "Компьютерный класс"),
                            ("sports", "Спортивный зал"),
                            ("assembly", "Актовый зал"),
                            ("office", "Кабинет"),
                            ("library", "Библиотека"),
                            ("other", "Другое"),
                        ],
                        max_length=20,
                        verbose_name="Тип",
                    ),
                ),
                (
                    "capacity",
                    models.PositiveSmallIntegerField(verbose_name="Вместимость"),
                ),
                (
                    "has_projector",
                    models.BooleanField(default=False, verbose_name="Проектор"),
                ),
                (
                    "has_computers",
                    models.BooleanField(default=False, verbose_name="Компьютеры"),
                ),
                (
                    "computers_count",
                    models.PositiveSmallIntegerField(
                        default=0, verbose_name="Количество компьютеров"
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="Описание")),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Активна"),
                ),
                (
                    "building",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rooms",
                        to="university_structure.building",
                    ),
                ),
            ],
            options={
                "verbose_name": "аудитория",
                "verbose_name_plural": "аудитории",
                "unique_together": {("building", "number")},
            },
        ),
        migrations.CreateModel(
            name="Holiday",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Название")),
                ("start_date", models.DateField(verbose_name="Дата начала")),
                ("end_date", models.DateField(verbose_name="Дата окончания")),
                (
                    "holiday_type",
                    models.CharField(
                        choices=[
                            ("public", "Государственный праздник"),
                            ("vacation", "Каникулы"),
                            ("university", "Праздник университета"),
                            ("other", "Другое"),
                        ],
                        max_length=20,
                        verbose_name="Тип",
                    ),
                ),
                (
                    "academic_year",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="holidays",
                        to="university_structure.academicyear",
                    ),
                ),
            ],
            options={
                "verbose_name": "праздник/выходной",
                "verbose_name_plural": "праздники/выходные",
            },
        ),
        migrations.AddField(
            model_name="group",
            name="specialization",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="groups",
                to="university_structure.specialization",
            ),
        ),
        migrations.CreateModel(
            name="Equipment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Название")),
                (
                    "inventory_number",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="Инвентарный номер"
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="Описание")),
                (
                    "purchase_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Дата приобретения"
                    ),
                ),
                (
                    "last_service_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Дата последнего ТО"
                    ),
                ),
                (
                    "room",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="equipment",
                        to="university_structure.room",
                    ),
                ),
            ],
            options={
                "verbose_name": "оборудование",
                "verbose_name_plural": "оборудование",
            },
        ),
        migrations.AddField(
            model_name="educationalprofile",
            name="specialization",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="profiles",
                to="university_structure.specialization",
            ),
        ),
        migrations.AddField(
            model_name="department",
            name="faculty",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="departments",
                to="university_structure.faculty",
            ),
        ),
        migrations.AddField(
            model_name="academicplan",
            name="profile",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="academic_plans",
                to="university_structure.educationalprofile",
            ),
        ),
        migrations.AddField(
            model_name="academicplan",
            name="specialization",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="academic_plans",
                to="university_structure.specialization",
            ),
        ),
        migrations.CreateModel(
            name="SubgroupStudent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subgroups",
                        to="accounts.studentprofile",
                    ),
                ),
                (
                    "subgroup",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="students",
                        to="university_structure.subgroup",
                    ),
                ),
            ],
            options={
                "verbose_name": "студент подгруппы",
                "verbose_name_plural": "студенты подгрупп",
                "unique_together": {("student", "subgroup")},
            },
        ),
        migrations.CreateModel(
            name="Semester",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "number",
                    models.PositiveSmallIntegerField(verbose_name="Номер семестра"),
                ),
                (
                    "semester_type",
                    models.CharField(
                        choices=[
                            ("autumn", "Осенний"),
                            ("spring", "Весенний"),
                            ("summer", "Летний"),
                        ],
                        max_length=10,
                        verbose_name="Тип",
                    ),
                ),
                ("start_date", models.DateField(verbose_name="Дата начала")),
                ("end_date", models.DateField(verbose_name="Дата окончания")),
                (
                    "class_start_date",
                    models.DateField(verbose_name="Дата начала занятий"),
                ),
                (
                    "class_end_date",
                    models.DateField(verbose_name="Дата окончания занятий"),
                ),
                (
                    "exam_start_date",
                    models.DateField(verbose_name="Дата начала сессии"),
                ),
                (
                    "exam_end_date",
                    models.DateField(verbose_name="Дата окончания сессии"),
                ),
                (
                    "is_current",
                    models.BooleanField(default=False, verbose_name="Текущий"),
                ),
                (
                    "academic_year",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="semesters",
                        to="university_structure.academicyear",
                    ),
                ),
            ],
            options={
                "verbose_name": "семестр",
                "verbose_name_plural": "семестры",
                "ordering": ["-academic_year__start_date", "number"],
                "unique_together": {("academic_year", "number")},
            },
        ),
        migrations.AlterUniqueTogether(
            name="group",
            unique_together={("name", "year_of_admission")},
        ),
        migrations.AlterUniqueTogether(
            name="educationalprofile",
            unique_together={("specialization", "name")},
        ),
        migrations.CreateModel(
            name="AcademicPlanSubject",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("semester", models.PositiveSmallIntegerField(verbose_name="Семестр")),
                (
                    "lectures_hours",
                    models.PositiveSmallIntegerField(default=0, verbose_name="Лекции"),
                ),
                (
                    "seminars_hours",
                    models.PositiveSmallIntegerField(
                        default=0, verbose_name="Семинары"
                    ),
                ),
                (
                    "labs_hours",
                    models.PositiveSmallIntegerField(
                        default=0, verbose_name="Лабораторные"
                    ),
                ),
                (
                    "practices_hours",
                    models.PositiveSmallIntegerField(
                        default=0, verbose_name="Практики"
                    ),
                ),
                (
                    "self_study_hours",
                    models.PositiveSmallIntegerField(
                        default=0, verbose_name="Самостоятельная работа"
                    ),
                ),
                (
                    "credits",
                    models.PositiveSmallIntegerField(verbose_name="Зачетные единицы"),
                ),
                (
                    "control_form",
                    models.CharField(
                        choices=[
                            ("exam", "Экзамен"),
                            ("credit", "Зачет"),
                            ("credit_grade", "Зачет с оценкой"),
                            ("coursework", "Курсовая работа"),
                            ("coursework_project", "Курсовой проект"),
                            ("state_exam", "Государственный экзамен"),
                            ("practice", "Практика"),
                            ("vkr_protection", "Защита ВКР"),
                        ],
                        max_length=20,
                        verbose_name="Форма контроля",
                    ),
                ),
                (
                    "is_optional",
                    models.BooleanField(
                        default=False, verbose_name="Дисциплина по выбору"
                    ),
                ),
                (
                    "academic_plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subjects",
                        to="university_structure.academicplan",
                    ),
                ),
                (
                    "subject",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="academic_plans",
                        to="university_structure.subject",
                    ),
                ),
            ],
            options={
                "verbose_name": "дисциплина учебного плана",
                "verbose_name_plural": "дисциплины учебного плана",
                "unique_together": {("academic_plan", "subject", "semester")},
            },
        ),
        migrations.AlterUniqueTogether(
            name="academicplan",
            unique_together={("specialization", "profile", "year", "version")},
        ),
    ]
